### PR TITLE
Map readout

### PR DESCRIPTION
**Pull request by nilscb**

### CODE REVIEW

**Review by hkfb — CHANGES_REQUESTED** [review]

**Review by hkfb — CHANGES_REQUESTED** [review]
The kh netmap example yields incorrect readout values

**Comment by shadab-skhan** [comment]
> The kh netmap example yields incorrect readout values

For me too the depth value seem to differ

**Comment by hkfb** [comment]
> > The kh netmap example yields incorrect readout values
> 
> For me too the depth value seem to differ

The difference seems to be within the bounds of the `meshMaxError` threshold, which is expected.

**Review by hkfb — APPROVED** [review]
Tested in the PPA Dashboard and works fine with the readout callback. Would be nice to have a storybook example using a `onMouseEvent` callback.

**Pull request merged**
