### PR TITLE
fix: speedup well log viewer

### PR DESCRIPTION
**Pull request by fbosquet-azpn**
bump videx-welllog to 0.9.2
introduce new label rotation for facies track

### CODE REVIEW

**Comment by hkfb** [comment]
The `prettier` conditions can be fixed with `npm run format`

See https://github.com/equinor/webviz-subsurface-components/tree/master/typescript#smoke-tests on updating the testing snapshots

**Comment by fbosquet-azpn** [comment]
> The `prettier` conditions can be fixed with `npm run format`
> 
> See https://github.com/equinor/webviz-subsurface-components/tree/master/typescript#smoke-tests on updating the testing snapshots

Unfortunatly `npm run docker:storybook:test` is failling for me.

Here is the error message
```
> docker:storybook:test
> docker run -it --rm --mount type=bind,source=.,target=/test --network host --ipc=host wsc_story_test


> storybook:test
> test-storybook

[test-storybook] 
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to       
install a platform-specific binary executable.

Specifically the "@esbuild/win32-x64" package is present but this platform
needs the "@esbuild/linux-x64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead of npm which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.


Error:
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/win32-x64" package is present but this platform
needs the "@esbuild/linux-x64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead of npm which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

    at generateBinPath (/test/node_modules/esbuild/lib/main.js:1888:17)
    at esbuildCommandAndArgs (/test/node_modules/esbuild/lib/main.js:1969:33)
    at ensureServiceIsRunning (/test/node_modules/esbuild/lib/main.js:2133:25)
    at startSyncServiceWorker (/test/node_modules/esbuild/lib/main.js:2336:19)
    at Object.<anonymous> (/test/node_modules/esbuild/lib/main.js:2377:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
```

**Comment by hkfb** [comment]
> > See https://github.com/equinor/webviz-subsurface-components/tree/master/typescript#smoke-tests on updating the testing snapshots
> 
> Unfortunately `npm run docker:storybook:test` is failing for me.
> 
> Here is the error message. (from my windows computer)
> 
> ```
> > docker:storybook:test
> > docker run -it --rm --mount type=bind,source=.,target=/test --network host --ipc=host wsc_story_test
> 
> 
> > storybook:test
> > test-storybook
> 
> [test-storybook] 
> You installed esbuild for another platform than the one you're currently using.
> This won't work because esbuild is written with native code and needs to       
> install a platform-specific binary executable.
> 
> Specifically the "@esbuild/win32-x64" package is present but this platform
> needs the "@esbuild/linux-x64" package instead. People often get into this
> situation by installing esbuild on Windows or macOS and copying "node_modules"
> into a Docker image that runs Linux, or by copying "node_modules" between
> Windows and WSL environments.
> 
> If you are installing with npm, you can try not copying the "node_modules"
> directory when you copy the files over, and running "npm ci" or "npm install"
> on the destination platform after the copy. Or you could consider using yarn
> instead of npm which has built-in support for installing a package on multiple
> platforms simultaneously.
> 
> If you are installing with yarn, you can try listing both this platform and the
> other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
> feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
> Keep in mind that this means multiple copies of esbuild will be present.
> 
> Another alternative is to use the "esbuild-wasm" package instead, which works
> the same way on all platforms. But it comes with a heavy performance cost and
> can sometimes be 10x slower than the "esbuild" package, so you may also not
> want to do that.
> 
> 
> Error:
> You installed esbuild for another platform than the one you're currently using.
> This won't work because esbuild is written with native code and needs to
> install a platform-specific binary executable.
> 
> Specifically the "@esbuild/win32-x64" package is present but this platform
> needs the "@esbuild/linux-x64" package instead. People often get into this
> situation by installing esbuild on Windows or macOS and copying "node_modules"
> into a Docker image that runs Linux, or by copying "node_modules" between
> If you are installing with npm, you can try not copying the "node_modules"
> directory when you copy the files over, and running "npm ci" or "npm install"
> on the destination platform after the copy. Or you could consider using yarn
> instead of npm which has built-in support for installing a package on multiple
> platforms simultaneously.
> 
> If you are installing with yarn, you can try listing both this platform and the
> other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
> feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
> Keep in mind that this means multiple copies of esbuild will be present.
> 
> Another alternative is to use the "esbuild-wasm" package instead, which works
> the same way on all platforms. But it comes with a heavy performance cost and
> can sometimes be 10x slower than the "esbuild" package, so you may also not
> want to do that.
> 
>     at generateBinPath (/test/node_modules/esbuild/lib/main.js:1888:17)
>     at esbuildCommandAndArgs (/test/node_modules/esbuild/lib/main.js:1969:33)
>     at ensureServiceIsRunning (/test/node_modules/esbuild/lib/main.js:2133:25)
>     at startSyncServiceWorker (/test/node_modules/esbuild/lib/main.js:2336:19)
>     at Object.<anonymous> (/test/node_modules/esbuild/lib/main.js:2377:3)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
> npm notice
> npm notice New major version of npm available! 9.8.1 -> 10.5.0
> npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
> npm notice Run npm install -g npm@10.5.0 to update!
> npm notice
> ```

I see, should probably change the approach for building the docker image.

I'll submit new snapshots to this PR.

**Review by hkfb — APPROVED** [review]
LGTM :+1:

**Comment by fbosquet-azpn** [comment]
The new reference images look good to me too.

**Pull request merged**
