### PR TITLE
Labels for views

### LINKED ISSUE #773: Labels for views
Optionally show label on each view

### PR DESCRIPTION
**Pull request by shadab-skhan**
"views": {
      "showLabel": false,
      "viewports": [
        {
          "id": "view_1",
          "name"?: "Main view",
          "show3D"?: false,
          "layerIds":? []
        }
      ]
    }

Default label is generated if not supplied. Label visibility is controlled by a global flag "showLabel".
Closes #773

### CODE REVIEW

**Review by hkfb — CHANGES_REQUESTED** [review]
The label should be optional, in case it does not match the style of the consumer.

**Comment by shadab-skhan** [comment]
> The label should be optional, in case it does not match the style of the consumer.

The label is optional, if it's not specified, the component will generate default labels like "View 1", "View 2", ...
Did you meant something else?

**Comment by hkfb** [comment]
> > The label should be optional, in case it does not match the style of the consumer.
> 
> The label is optional, if it's not specified, the component will generate default labels like "View 1", "View 2", ... Did you meant something else?

Yes, I meant by default there should be no label at all. At least this is my opinion.

**Comment by shadab-skhan** [comment]
> > > The label should be optional, in case it does not match the style of the consumer.
> > 
> > 
> > The label is optional, if it's not specified, the component will generate default labels like "View 1", "View 2", ... Did you meant something else?
> 
> Yes, I meant by default there should be no label at all. At least this is my opinion.

Done! Now if name is supplied, it will be used to label the in viewport. Visibility of name is controlled by a global flag.

**Pull request merged**
