### PR TITLE
feat!: Refactor utils and provide WellCompletionsPlot utility-lib

### PR DESCRIPTION
**Pull request by jorgenherje**
WellCompletionsPlot is a simple component responsible to plot data provided as is. 

The need for preprossessing of the plot data might occur, e.g.:
- sorting of wells based on various selections 
- extraction of data subzones from a zone tree structure in plotData
- regex match for well name 

---

PR includes changes:
- Create utility lib for handling plot data for the WellCompletionsPlot component
- Use new utils in WellCompletions-component (Dash-component) where applicable

BREAKING CHANGE: code reorganization

### CODE REVIEW

**Comment by hkfb** [comment]
The story snapshots that are not related to this change, should not have changed. Maybe you can revert them?

**Comment by hkfb** [comment]
Technically it's a breaking change (ie. "breaking" prefix), since the interface of `WellCompletionsPlot` has changed.

Otherwise LGTM 👍

**Review by hkfb — APPROVED** [review]

**Comment by jorgenherje** [comment]
> Technically it's a breaking change (ie. "breaking" prefix), since the interface of `WellCompletionsPlot` has changed.
> 
> Otherwise LGTM 👍

"breaking" does not seem to be a valid prefix: https://github.com/equinor/webviz-subsurface-components/actions/runs/11008300403/job/30565681314?pr=2251

**Comment by hkfb** [comment]
> > Technically it's a breaking change (ie. "breaking" prefix), since the interface of `WellCompletionsPlot` has changed.
> > Otherwise LGTM 👍
> 
> "breaking" does not seem to be a valid prefix: https://github.com/equinor/webviz-subsurface-components/actions/runs/11008300403/job/30565681314?pr=2251

Right, could you try again the "feat" prefix, but add "BREAKING CHANGE: <something>" in the PR description?

**Comment by w1nklr** [comment]
> > > Technically it's a breaking change (ie. "breaking" prefix), since the interface of `WellCompletionsPlot` has changed.
> > > Otherwise LGTM 👍
> > 
> > 
> > "breaking" does not seem to be a valid prefix: https://github.com/equinor/webviz-subsurface-components/actions/runs/11008300403/job/30565681314?pr=2251
> 
> Right, could you try again the "feat" prefix, but add "BREAKING CHANGE: " in the PR description?

try "feat!: ". The ! is for a breaking change.
 But it's a good idea to add the "BREAKING CHANGE: "

I'm not sure, but we might follow the angular coding rules:
- https://www.conventionalcommits.org/en/v1.0.0/ (this link comes from the pipeline error)
- https://github.com/angular/angular/blob/main/CONTRIBUTING.md#rules

**Review by w1nklr — APPROVED** [review]

**Comment by jorgenherje** [comment]
> > > > Technically it's a breaking change (ie. "breaking" prefix), since the interface of `WellCompletionsPlot` has changed.
> > > > Otherwise LGTM 👍
> > > 
> > > 
> > > "breaking" does not seem to be a valid prefix: https://github.com/equinor/webviz-subsurface-components/actions/runs/11008300403/job/30565681314?pr=2251
> > 
> > 
> > Right, could you try again the "feat" prefix, but add "BREAKING CHANGE: " in the PR description?
> 
> try "feat!: ". The ! is for a breaking change. But it's a good idea to add the "BREAKING CHANGE: "
> 
> I'm not sure, but we might follow the angular coding rules:
> 
> * https://www.conventionalcommits.org/en/v1.0.0/ (this link comes from the pipeline error)
> * https://github.com/angular/angular/blob/main/CONTRIBUTING.md#rules
> 
> Edit: I played around with your PR title and description to test it ;)

Thanks for the help!

**Pull request merged**
