### PR TITLE
Typecheck error in DeckGlMap 

### LINKED ISSUE #900: Typecheck error in DeckGlMap
Running the following commands
```
rm package-lock.json
rm -rf node_modules
npm i --ignore-scripts --legacy-peer-deps
npm run setup-deckgl-types
npm run typecheck
```
Fails with following error
```
src/lib/components/DeckGLMap/DeckGLMap.tsx:107:15 - error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

107         store.dispatch(setSpec(spec));
                  ~~~~~~~~

src/lib/components/DeckGLMap/test/TestWrapper.tsx:7:1 - error TS2322: Type 'Mock<any, any>' is not assignable to type 'never'.

7 testStore.dispatch = jest.fn();
  ~~~~~~~~~~~~~~~~~~

src/lib/components/DeckGLMap/test/TestWrapper.tsx:17:1 - error TS2322: Type 'Mock<any, any>' is not assignable to type 'never'.

17 emptytestStore.dispatch = jest.fn();
   ~~~~~~~~~~~~~~~~~~~~~~~

src/lib/components/GroupTree/test/TestWrapper.tsx:11:1 - error TS2322: Type 'Mock<any, any>' is not assignable to type 'never'.

11 testStore.dispatch = jest.fn();
   ~~~~~~~~~~~~~~~~~~

src/lib/components/WellCompletions/test/TestWrapper.tsx:11:1 - error TS2322: Type 'Mock<any, any>' is not assignable to type 'never'.

11 testStore.dispatch = jest.fn();
   ~~~~~~~~~~~~~~~~~~


Found 5 errors.
```

### PR DESCRIPTION
**Pull request by shadab-skhan**
Fix #900

### CODE REVIEW

**Comment by HansKallekleiv** [comment]
The reason it fails the python test is due to console errors:
Not entirely sure if its python related. Any thoughts?
```
react-dom@16.v2_3_0m1647948465.14.0.min.js:125 
        
       Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (useReduxContext.js?9825:24:1)
    at useStore (useStore.js?cb87:20:1)
    at useDispatch (useDispatch.js?ee24:17:1)
    at DeckGLMap (DeckGLMap.tsx?8062:101:33)
    at we (react-dom@16.v2_3_0m1647948465.14.0.min.js:84:293)
    at zj (react-dom@16.v2_3_0m1647948465.14.0.min.js:226:496)
    at Th (react-dom@16.v2_3_0m1647948465.14.0.min.js:152:223)
    at tj (react-dom@16.v2_3_0m1647948465.14.0.min.js:152:152)
    at Te (react-dom@16.v2_3_0m1647948465.14.0.min.js:146:151)
    at react-dom@16.v2_3_0m1647948465.14.0.min.js:61:68
    ```

**Comment by hkfb** [comment]
>        Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

Looks like the `dispatch` call needs to be nested below the `<Provider>`: https://stackoverflow.com/questions/60329421/usedispatch-error-could-not-find-react-redux-context-value-please-ensure-the

**Comment by shadab-skhan** [comment]
> The reason it fails the python test is due to console errors: Not entirely sure if its python related. Any thoughts?
> 
> ```
> react-dom@16.v2_3_0m1647948465.14.0.min.js:125 
>         
>        Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
>     at useReduxContext (useReduxContext.js?9825:24:1)
>     at useStore (useStore.js?cb87:20:1)
>     at useDispatch (useDispatch.js?ee24:17:1)
>     at DeckGLMap (DeckGLMap.tsx?8062:101:33)
>     at we (react-dom@16.v2_3_0m1647948465.14.0.min.js:84:293)
>     at zj (react-dom@16.v2_3_0m1647948465.14.0.min.js:226:496)
>     at Th (react-dom@16.v2_3_0m1647948465.14.0.min.js:152:223)
>     at tj (react-dom@16.v2_3_0m1647948465.14.0.min.js:152:152)
>     at Te (react-dom@16.v2_3_0m1647948465.14.0.min.js:146:151)
>     at react-dom@16.v2_3_0m1647948465.14.0.min.js:61:68
>     ```
> ```

Thanks Hans, I couldn't see this error message, this need to be fixed on JS side will make the changes.

**Comment by shadab-skhan** [comment]
> > ```
> >    Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
> > ```
> 
> Looks like the `dispatch` call needs to be nested below the `<Provider>`: https://stackoverflow.com/questions/60329421/usedispatch-error-could-not-find-react-redux-context-value-please-ensure-the

Thanks for the tip @hkfb

**Review by hkfb — APPROVED** [review]

**Pull request merged**
