### PR TITLE
Make dash wrapper for color legend component

### PR DESCRIPTION
**Pull request by shruthirai**
Fixes https://github.com/equinor/webviz-subsurface-components/issues/1390 and https://github.com/equinor/webviz-subsurface-components/issues/1410

### CODE REVIEW

**Review by HansKallekleiv — CHANGES_REQUESTED** [review]
This looks good!

A minor addition is needed for it work from Dash:
The component must be imported and exported from the top-level index.js

**Comment by shruthirai** [comment]
@HansKallekleiv I have mentioned this already in https://github.com/equinor/webviz-subsurface-components/issues/1410 at the end ,  you can still use "continuous legend", if you pass different colorName and id prop to the continuous legend , it works. May be you are missing the id prop.

**Review by HansKallekleiv — APPROVED** [review]
👍

**Review by HansKallekleiv — CHANGES_REQUESTED** [review]
One remaining issue with the allocated space of the color legend. The values are truncated.
I tried changing `legendFontSize` but it does not appear to have any effect.

image

image

**Comment by shruthirai** [comment]
> One remaining issue with the allocated space of the color legend. The values are truncated. I tried changing `legendFontSize` but it does not appear to have any effect. Increasing the size of the svg manually show the full value.
> 
> image
> 
> image

Will fix it

**Review by hkfb — APPROVED** [review]

**Review by HansKallekleiv — APPROVED** [review]
LGTM

**Pull request merged**
