### PR TITLE
Viewport is reset when picking

### LINKED ISSUE #974: Viewport is reset when picking
When picking close to the lower edge of the canvas, eg. picking a well trajectory, the viewport resets.

Seems to be caused by the tooltip, which causes a scrollbar to appear.

### PR DESCRIPTION
**Pull request by shadab-skhan**
Fixes #974

### CODE REVIEW

**Review by hkfb — CHANGES_REQUESTED** [review]
I still get the viewport reset behaviour..

**Comment by shadab-skhan** [comment]
@hkfb I have updated the change, reset issue should not persist any more

**Review by hkfb — APPROVED** [review]
The viewport doesn't reset any longer, but it still shakes when the tooltip is shown overlapping the bottom edge of the viewport.

Also, the following error is shown when I alter the bounds prop:
```
Assertion failed: console.assert
fitBounds	@	fit-bounds.jss:60
getViewState	@	Map.tsxx:596
Map	@	Map.tsxx:229
renderWithHooks	@	react-dom.development.jss:14985
updateFunctionComponent	@	react-dom.development.jss:17356
beginWork	@	react-dom.development.jss:19063
beginWork$1	@	react-dom.development.jss:23940
performUnitOfWork	@	react-dom.development.jss:22779
workLoopSync	@	react-dom.development.jss:22707
renderRootSync	@	react-dom.development.jss:22670
performSyncWorkOnRoot	@	react-dom.development.jss:22293
(anonymous)	@	react-dom.development.jss:11327
unstable_runWithPriority	@	scheduler.development.jss:468
runWithPriority$1	@	react-dom.development.jss:11276
flushSyncCallbackQueueImpl	@	react-dom.development.jss:11322
flushSyncCallbackQueue	@	react-dom.development.jss:11309
scheduleUpdateOnFiber	@	react-dom.development.jss:21893
updateContainer	@	react-dom.development.jss:25482
legacyRenderSubtreeIntoContainer	@	react-dom.development.jss:26037
render	@	react-dom.development.jss:26103
(anonymous)	@	render.jss:62
_callee$	@	render.jss:61
tryCatch	@	core-react.umd.jss:3466
invoke	@	core-react.umd.jss:3696
(anonymous)	@	core-react.umd.jss:3521
asyncGeneratorStep	@	render.jss:36
_next	@	render.jss:38
(anonymous)	@	render.jss:38
(anonymous)	@	render.jss:38
renderElement	@	render.jss:76
Promise.then (async)		
asyncGeneratorStep	@	PreviewWeb.jss:8
_next	@	PreviewWeb.jss:10
(anonymous)	@	PreviewWeb.jss:10
(anonymous)	@	PreviewWeb.jss:10
render	@	PreviewWeb.jss:1185
rerenderStoryIfMatches	@	PreviewWeb.jss:1207
(anonymous)	@	index.jss:168
handleEvent	@	index.jss:167
(anonymous)	@	index.jss:52
handler	@	index.jss:100
handleEvent	@	index.jss:285
postMessage (async)		
(anonymous)	@	vendors-node_modules…ger.bundle.js:41161
send	@	vendors-node_modules…ger.bundle.js:41159
handler	@	vendors-node_modules…ger.bundle.js:12632
emit	@	vendors-node_modules…ger.bundle.js:12642
emit	@	vendors-node_modules…ager.bundle.js:9235
updateStoryArgs	@	vendors-node_modules…ger.bundle.js:10321
(anonymous)	@	vendors-node_modules…ger.bundle.js:12309
(anonymous)	@	vendors-node_modules…ger.bundle.js:14933
onUpdate	@	vendors-node_modules…ger.bundle.js:20599
(anonymous)	@	vendors-node_modules…ger.bundle.js:19539
Promise.then (async)		
(anonymous)	@	vendors-node_modules…ger.bundle.js:19527
handleEditValue	@	vendors-node_modules…ger.bundle.js:19518
handleEdit	@	vendors-node_modules…ger.bundle.js:18503
onKeydown	@	vendors-node_modules…ger.bundle.js:18473
```

**Comment by shadab-skhan** [comment]
It asserts when width and height of the viewport is 0, else it should be fine.
`    const targetSize = [
        width - padding.left - padding.right - Math.abs(offset[0]) * 2,
        height - padding.top - padding.bottom - Math.abs(offset[1]) * 2,
    ];
    console.assert(targetSize[0] > 0 && targetSize[1] > 0);
`

**Pull request merged**
