### PR TITLE
chore: bump videx from 0.9.2 to 0.9.4 in /typescript/packages/well-log-viewer

### PR DESCRIPTION
**Pull request by Vladimir-Kokin**

### CODE REVIEW

**Review by t0oF-azpn — APPROVED** [review]

**Comment by hkfb** [comment]
@anders-kiaer any idea why the python workflow is failing?

**Comment by w1nklr** [comment]
I restarted them and they are green now 😉

But the storybook is still failing 😕

toF

Christophe Winkler
Principal Software Developer
work: +33 383674876  |  www.aspentech.com<http://www.aspentech.com>





AspenTech Europe SA NV 1-7 Cours Valmy, 92800 Puteaux
Siège social de la société: 1-7 Cours Valmy, 92800 Puteaux
avec bureau à l’étranger: Aspen Technology, Inc., Siège social 20 Crosby Drive, Bedford, MA01730, USA, avec numéro d’enregistrement 2859683

________________________________

**Comment by Vladimir-Kokin** [comment]
I have updated test images with
`npm run docker:storybook:test:update`
But smoke test still failed

**Comment by Vladimir-Kokin** [comment]
I just repeat run of check jobs 4 times and now storybook test is successfull

**Comment by w1nklr** [comment]
> I just repeat run of check jobs 4 times and now storybook test is successfull

I fear that this means that we introduce flaky test (unstable tests that are randomly failing).
I hope not, this is a nightmare...

**Pull request merged**
