### PR TITLE
Adding more props to continuous legend for dash support

### PR DESCRIPTION
**Pull request by shruthirai**
Fix for missing tick mark prop issue(first point) https://github.com/equinor/webviz-subsurface-components/issues/1410

### CODE REVIEW

**Comment by shruthirai** [comment]
@hkfb I can create another PR for exposing the ColorLegend component to Dash but maybe for time being lets keep continouslegend until then.

**Comment by shruthirai** [comment]
Fixes missing tick mark prop issue(first point) https://github.com/equinor/webviz-subsurface-components/issues/1410

**Comment by shruthirai** [comment]
> @hkfb @HansKallekleiv I can create another PR for exposing the ColorLegend component to Dash as suggested by Hans but maybe for time being lets keep continouslegend until then.

**Review by hkfb — COMMENTED** [review]
Please link to an issue. Create a new issue if necessary.

**Comment by shruthirai** [comment]
> Please link to an issue. Create a new issue if necessary.

I have linked it above

**Comment by shruthirai** [comment]
> > Please link to an issue. Create a new issue if necessary.
> 
> I have already linked it above

**Comment by shruthirai** [comment]
@hkfb Should I merge this ?

**Review by hkfb — APPROVED** [review]

**Pull request merged**
