### PR TITLE
fix: camera state when hidden page is rendered

### PR DESCRIPTION
**Pull request by t0oF-azpn**
Fix for #1820 

Add formal size state and effect to retrieve size from deck ref for code clarity
Move global bounding box handling to React reducer instead of useEffect.
Move camera computation to useMemo instead of useEffect.
Memoize viewPortMargins and deckGLLayers

Add a new story displaying the subsurface viewer in tabs to reproduce the issue

Note that this is a first step to reduce the number of useEffect in the Map component

### CODE REVIEW

**Comment by hkfb** [comment]
> Note that this is a first step to reduce the number of useEffect in the Map component

This is just refactoring and creating an example to demonstrate the bug?

**Review by nilscb — APPROVED** [review]

**Comment by t0oF-azpn** [comment]
> > Note that this is a first step to reduce the number of useEffect in the Map component
> 
> This is just refactoring and creating an example to demonstrate the bug?

Nope, it fixes also the bug (ie. the example was showing the bug before I fixed it in the same PR)

**Review by hkfb — COMMENTED** [review]
I get this error in the console: 
image
Not sure if it's related to your change though.

**Review by hkfb — COMMENTED** [review]
The second tab seems wrongly initialized the first time it's opened:
image
The second time I open it I can see the map.

**Comment by t0oF-azpn** [comment]
> The second tab seems wrongly initialized the first time it's opened: image The second time I open it I can see the map.

:/
How are you doing ?
What is your browser ??

**Review by hkfb — APPROVED** [review]

**Pull request merged**
