### PR TITLE
Dynamic Tree

### LINKED ISSUE #47: Add Eclipse GRUPTREE visualization

### PR DESCRIPTION
**Pull request by anders-kiaer**
Closes #47.

### CODE REVIEW

**Comment by asnyv** [comment]
Haven't looked at it yet, but do you also support the extended network option, or just regular GRUPTREE/GRUPNET combo?

**Comment by anders-kiaer** [comment]
> Haven't looked at it yet, but do you also support the extended network option, or just regular GRUPTREE/GRUPNET combo?

The main assumption by the component itself is only that the network has a "tree structure" (i.e. any node has only one branch connected to it in the direction of the terminal node at the top of the tree). The tree structure can change through time.

**Comment by asnyv** [comment]
Was thinking more if it made assumptions on keywords and etc, but would think that is handled by how we wrap it and give json-input?

E.g. in Eclipse you can either use the standard network option with `GRUPTREE` and `GRUPNET`, or the extended option with `BRANPROP` and `NODEPROP` which is freed from your grupnet, allowing you to have independent production group reports and actual flow networks. Still a tree structure, just a bit different input.

**Comment by anders-kiaer** [comment]
Yes, I think the dependendices of keywords will first enter on the `webviz-subsurface` plugin. The component itself will probably be agnostic and independent of keyword (and instead have parameter names indicating what it is used for in the visualization).

**Comment by anders-kiaer** [comment]
Closing the prototype PR. To be replaced with a new component.

**Pull request closed without merging**
