### PR TITLE
feat: Automatic zoom to fit data bounds

### LINKED ISSUE #689: Automatic zoom to fit data bounds
Default zoom to automatically fit data bounds if manual zoom is not set.

Data should fit into the initial viewport of the container.

### PR DESCRIPTION
**Pull request by shadab-skhan**
Fix #689

### CODE REVIEW

**Comment by hkfb** [comment]
The failing check is maybe related to this issue: https://github.com/plotly/dash/issues/1992

**Comment by avanti-em** [comment]
> @avanti-em I guess we need to learn how to regenerate the reference screenshots :)

I think I should implement an automatic images update process (via a PR by some bot).
I will try to search about it.
For now I will update the new images

**Review by avanti-em — APPROVED** [review]

**Comment by avanti-em** [comment]
Corresponding snapshots added in this PR

**Review by avanti-em — APPROVED** [review]

**Review by hkfb — APPROVED** [review]
Nice improvement! But it doesn't seem to work on all layers.

**Pull request merged**
