### PR TITLE
Semantic release dry-run

### PR DESCRIPTION
**Pull request by hkfb**
Dry-run semantic release on merge to master.

For each package, except `dash-components`

* Bump version number
* Update changelog
* Update github release
* Publish NPM package

### CODE REVIEW

**Comment by hkfb** [comment]
> So each merge to master will trigger new releases in the end (I understand it's dry run for now) ?

It's just a dry run for now, but once enabled it should check the commits since last release for anything that is release "worthy", eg. any `fix: ...`, `patch: ...`, `feat: ...`, etc. If so, it should then check which packages have been affected (by checking which files have been modified), bump their version number and release only those.

**Comment by asnyv** [comment]
Hi, I am out of office for around a week. @rubenthoms did you (or could you) have a look at this?

**Review by rubenthoms — COMMENTED** [review]
@asnyv Looks good to me. 

Note, however, that the package used for **nx**-semantic-release does not yet have gotten a security review on Snyk and its popularity/community is rather limited:
https://snyk.io/advisor/npm-package/@theunderscorer/nx-semantic-release

**Comment by hkfb** [comment]
> @asnyv Looks good to me.
> 
> Note, however, that the package used for **nx**-semantic-release does not yet have gotten a security review on Snyk and its popularity/community is rather limited: https://snyk.io/advisor/npm-package/@theunderscorer/nx-semantic-release

Thanks for the review @rubenthoms. I think this is the most promising package I could find for monorepo semantic release, although it's unfortunate that it's missing a security review. Suggest that we go ahead and merge this.

**Pull request merged**
