### PR TITLE
build: Bump Deck.gl to latest version.

### PR DESCRIPTION
**Pull request by nilscb**
-This should contain a fix for the scrolling issues we have experienced.

### CODE REVIEW

**Review by t0oF-azpn — APPROVED** [review]

**Review by hkfb — CHANGES_REQUESTED** [review]
Need to add your `package-lock.json` also.

**Comment by t0oF-azpn** [comment]
> Need to add your `package-lock.json` also.

Good catch !

**Review by hkfb — COMMENTED** [review]
Is it just me or do the wells look slightly blurred now?

image

**Comment by t0oF-azpn** [comment]
> Is it just me or do the wells look slightly blurred now?
> 
> image

They are blurred, but it is already the case in the published storybook (ie. if there is a regression, it does not come from this PR):

Image from the storybbok:
image

**Comment by hkfb** [comment]
> > Is it just me or do the wells look slightly blurred now?
> > image
> 
> They are blurred, but it is already the case in the published storybook (ie. if there is a regression, it does not come from this PR):
> 
> Image from the storybbok: image

The upper image looks more blurry to me.

**Comment by nilscb** [comment]
Its a bit hard to say. I agree that the upper appears slightly  more blurred

**Review by hkfb — APPROVED** [review]
I'll change to approved and let you decide. I think we should drop a note to deck.gl about the blurred polygons

**Comment by t0oF-azpn** [comment]
I confirm that there is no visible difference in full-screen on my machine.

**Pull request merged**
