### PR TITLE
feat: Allow camera xy scaling

### PR DESCRIPTION
**Pull request by hkfb**
Followup to https://github.com/equinor/webviz-subsurface-components/pull/2001

Also inverts amplitude of vertical scaling

Also removes unused png files from builds

Note that axis rendering instability persists. I have not found a solution, but we can follow it up.

### CODE REVIEW

**Comment by hkfb** [comment]
@nilscb What's interesting is that the axes are stable if `cameraPosition.target` is set to eg. `[1, 1, 1]`, but unstable when set to `[0, 0, 0]`

**Comment by nilscb** [comment]
Ok that is a good observation. I guess target (what the camera looks at) should be set to x,y = middle of data and z some negative value(?) I can look at t further after this PR.

**Review by nilscb — APPROVED** [review]

**Pull request merged**
