### PR TITLE
map and color legend tests

### PR DESCRIPTION
**Pull request by avanti-em**

### CODE REVIEW

**Comment by avanti-em** [comment]
Hi @hkfb , in this PR, the snapshot - ColorLegend.test.tsx.snap generated by ColorLegend.test.tsx. has null value
I think this could be because of changes made by me in jest.config.js. (where I have ignored some modules in "transformIgnorePatterns" )
But if I remove those changes it won't run.
Please take a look

**Comment by shruthirai** [comment]
> > Hi @hkfb , in this PR, the snapshot - ColorLegend.test.tsx.snap generated by ColorLegend.test.tsx. has null value I think this could be because of changes made by me in jest.config.js. (where I have ignored some modules in "transformIgnorePatterns" ) But if I remove those changes it won't run. Please take a look
> 
> I've heard about problems running jest tests on es6 targets. @emerson-eps/color-tables targets es6 (see tsconfig.json). Could this be the problem? @shruthirai we should try to target es5 instead.
> 
> Btw, the failing check seems to be related to this issue: [plotly/dash#1992](https://github.com/plotly/dash/issues/1992)

@avanti-em @hkfb I have made changes to the tesconfig.json but I think for avanti to access the changes the colortable version in webviz package also need to be changed as well right as it is taking old version.

**Comment by avanti-em** [comment]
> > > Hi @hkfb , in this PR, the snapshot - ColorLegend.test.tsx.snap generated by ColorLegend.test.tsx. has null value I think this could be because of changes made by me in jest.config.js. (where I have ignored some modules in "transformIgnorePatterns" ) But if I remove those changes it won't run. Please take a look
> > 
> > 
> > I've heard about problems running jest tests on es6 targets. @emerson-eps/color-tables targets es6 (see tsconfig.json). Could this be the problem? @shruthirai we should try to target es5 instead.
> > Btw, the failing check seems to be related to this issue: [plotly/dash#1992](https://github.com/plotly/dash/issues/1992)
> 
> @avanti-em @hkfb I have made changes to the tesconfig.json but I think for avanti to access the changes the colortable version in webviz package also need to be changed as well right as it is taking old version.

I updated it locally, but the issue is still there. I am trying to figure out something else or maybe remove that one particular test completly

**Comment by hkfb** [comment]
@avanti-em why does the coverage decrease with this change?

**Review by hkfb — APPROVED** [review]

**Review by hkfb — APPROVED** [review]

**Pull request merged**
